substitutions:
  # Settings - Editable values
  device_name: "nspanel_kitchen"
  friendly_name: "NSPanel Kitchen"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: !secret nspanel_update_url  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
esp32:
  framework:
    type: arduino
switch:
  # Prevents the two relays to be on simultaneously
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
cover:
  - platform: time_based
    name: "Kitchen Cover"
    id: kitchen_cover

    open_action:
      - switch.turn_on: relay_2
    open_duration: 20s

    close_action:
      - switch.turn_on: relay_1
    close_duration: 20s

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
